
import { GoogleGenAI } from "@google/genai";
import { SYSTEM_PROMPT } from "../constants";

export const generateColoringPage = async (prompt: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  const fullPrompt = `Generate a high-quality, clean black and white line art coloring page for a child. Subject: ${prompt}. The lines should be bold and clear. Pure white background. No colors or shading.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { text: fullPrompt },
          { text: "Rules: Strictly black and white line art. Bold outlines. No grayscale." }
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1"
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image was generated by Gemini.");
  } catch (error) {
    console.error("Gemini generation error:", error);
    throw error;
  }
};
